config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  
  # API routes
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      
      post '/auth' => 'auth#api_auth' # jwt authentication
      
      get 'events/nearby' => 'events#nearby' # get events close to a point, requires params :lat, :lng
      get 'events/query' => 'events#query' # get events on search
      
      resources :events        
      resources :tags do
        resources :events, only: [:index] # tags/1/events
      end
      resources :hunters do
        resources :events, only: [:index] # hunters/1/events
      end

      resources :hunters
  
    end
    #scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true) do
      #resources :events
    #end
  end
  
  # Registration routes
  root 'users#main'
  get 'register' => 'users#new' # show registry form
  post 'register' => 'users#create' # do register user
	get 'login' => 'sessions#new' # show login form
  post 'login' => 'sessions#create' # do login user
  get 'logout' => 'sessions#destroy' # do logout user - requires logged 
  resources :users, only: [:show, :index] # show specific user
  get 'add_key' => 'keys#create' # add new api key
  get 'remove_key' => 'keys#destroy' # remove api key
  get 'docs' => 'docs#index' # main page of documentation
  
  # Admin routes  
  get 'login_admin' => 'sessions#new_admin' # show admin login-form
  post 'login_admin' => 'sessions#create_admin' # do login admin
  get 'logout_admin' => 'sessions#destroy_admin' # do logout admin - requires logged
  resources :admins, only: [:show, :index] # show specific admin  
  get  "keys/remove/:id" => "keys#destroy_by_admin", as: :remove_key_by_admin # admin removes a users apikey
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :apikey, dependent: :destroy
  has_secure_password
        
  validates :password,
		length: { minimum: 5 }
  
  validates :email,
    presence: {message: "E-mail is required"},
    uniqueness: true
  
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
    presence: {message: "E-mail not valid"}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
 # before_action :require_login, except: [:index, :new, :create, :login]
  before_action :check_user, except: [:main, :new, :create]
  
  def main
    # if user is logged in, redirect to user-infopage
    # redirect_to @user
    # else render main page
  end
  
  def new
    # show registry form
    @user = User.new
  end
  
  def create
    # create user with post params
    @user = User.new(user_params)
    
    if @user.save
      # store session
      ## session[:userid] = @user.id
      redirect_to @user
    else
      # show registry form with errors
      render action: :new
      # or? redirect_to register_path
    end
  end

  def show
    # get current user        
    @user = current_user
    
    # check if correct user
  end 
  
  private
 
  # allowed parameters when creating account
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/main.html.erb
<% content_for :title, "home page" %>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<h1>Welcome to Trophy</h1>

<p>This is the main page for Trophy-api. From here you can</p>
<ul>
  <li>1) Create your developer account if you dont have one already</li>
  <li>2) Login to your account and manage your api-keys</li>
  <li>3) Read our awesome documentation that dosnt exist yet</li>
</ul>



<%= link_to "Register", register_path, class: "btn btn-success" %>
<%= link_to "Login", login_path, class: "btn btn-primary" %>
<%= link_to "Docs", docs_path, class: "btn btn-info" %>
<%= link_to "Admin", login_admin_path, class: "btn btn-danger" %>

app/views/users/new.html.erb
<% content_for :title, "register user" %>

<h1>Register new user</h1>

<% if @user.errors.any? %>
  <h2>Form errors:</h2>
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @user, :url => register_path do |u| %>
  <p><%= u.label :email, "E-mail" %><br />
  <%= u.email_field :email %></p>

  <p><%= u.label :password, "Password" %><br />
  <%= u.password_field :password %></p>
  
  <p><%= u.label :password_confirmation, "Confirm password" %><br />
  <%= u.password_field :password_confirmation %></p>

  <p><%= link_to "Go back", root_path, class: "btn btn-default" %>
    <%= u.submit "Register user", class: "btn btn-success" %></p>
<% end %>

app/views/users/show.html.erb
<% content_for :title, "user page" %>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<h1>Welcome <%= @user.email %></h1>

<% if @user.apikey.present? %>
  <%= @user.apikey.key.to_s %>
  <p><% @user.apikey  %></p>
<%= link_to "Remove key", remove_key_path, class: "btn btn-danger" %>
<% else %>
  <p>No key</p>
<%= link_to "Generate new key", add_key_path, class: "btn btn-success" %>
<% end %>
<%= link_to "Log out", logout_path, class: "btn btn-default" %>